"""Generate the Angular extension registry from append-only descriptors."""

from __future__ import annotations

import json
from pathlib import Path
import re
import sys

IDENTIFIER = re.compile(r"^[A-Za-z_$][A-Za-z0-9_$]*$")


def generate_registry(descriptors_dir: Path, output: Path) -> None:
    extensions: list[dict[str, object]] = []
    for descriptor_path in sorted(descriptors_dir.glob("*/extension.json")):
        data = json.loads(descriptor_path.read_text(encoding="utf-8"))
        component = data.get("componentClass")
        import_path = data.get("importPath")
        order = data.get("order", 1000)
        if not isinstance(component, str) or not IDENTIFIER.fullmatch(component):
            raise ValueError(f"{descriptor_path}: invalid componentClass")
        if not isinstance(import_path, str) or not import_path.startswith("../../extensions/"):
            raise ValueError(f"{descriptor_path}: importPath must target ../../extensions/")
        if not isinstance(order, int):
            raise ValueError(f"{descriptor_path}: order must be an integer")
        extensions.append({**data, "componentClass": component, "importPath": import_path, "order": order})

    extensions.sort(key=lambda item: (item["order"], item.get("id", "")))
    lines = [
        "// Generated by scripts/generate_extensions.py. Do not edit.",
        "import {Type} from '@angular/core';",
        "import {RentalExtensionComponent} from '../rental-extension';",
    ]
    for item in extensions:
        lines.append(f"import {{{item['componentClass']}}} from '{item['importPath']}';")
    lines.extend([
        "",
        "export const RENTAL_EXTENSION_COMPONENTS: Type<RentalExtensionComponent>[] = [",
        *[f"  {item['componentClass']}," for item in extensions],
        "];",
        "",
    ])
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        raise SystemExit("usage: generate_extensions.py DESCRIPTORS OUTPUT")
    generate_registry(Path(sys.argv[1]), Path(sys.argv[2]))
